FROM php:7.2-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
    	&& docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include \
    	&& docker-php-ext-install gd \
        && docker-php-ext-install mysqli \
        && docker-php-ext-enable mysqli
        && touch /usr/local/etc/php/conf.d/uploads.ini \
        && echo "upload_max_filesize = 10M;" >> /usr/local/etc/php/conf.d/uploads.ini