version: '3'
services:
  front:
      image: nginx:latest
      ports:
        - "88:80"
      volumes:
        - ./bin:/bin
        - ./src/web/app/uploads:/images
        - ./src/web/app/cache:/json
        - ./site-front.conf:/etc/nginx/conf.d/default.conf
  back:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/web:/src/web
      - ./site-back.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
      build:
        context: .
        dockerfile: Dockerfile-php
      volumes:
        - ./src/web:/src/web
        - ./src:/src
  mysql:
      image: mysql:5
      volumes:
        - "./data/db:/var/lib/mysql"
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: password
  composer:
      image: composer
      command: ["update","install"]
      volumes:
        - "./src:/app"
