version: '3'
services:
  front:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./bin:/bin
      - ./src/web/app/uploads:/images
      - ./src/web/app/cache:/json
      - ./site-front.conf:/etc/nginx/conf.d/default.conf
  back:
    restart: always
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./src/web:/src/web
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile-php
      volumes:
        - ./src/web:/src/web
        - ./src:/src
  mysql:
      image: mysql:5
      volumes:
        - "./data/db:/var/lib/mysql"
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: EibBGv6w4SsDzsPPHmC22RBpEmmsnPc
        MYSQL_DATABASE: galdnieks_001_database
        MYSQL_USER: rigasgaldnieks
        MYSQL_PASSWORD: 5XVitP6olq9a3wlXtzpIWG831QBpx8k
  composer:
      image: composer
      command: ["update","install"]
      volumes:
        - "./src:/app"
